// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0jy63kR8Ya33HE2LwFwCajnogVg-zRwo',
    appId: '1:161260576816:android:570a995f692de9ea210df5',
    messagingSenderId: '161260576816',
    projectId: 'ai-chatbot-505a7',
    storageBucket: 'ai-chatbot-505a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1LESfbbg8CrfgLI2Eyw-teydA0OiuxYs',
    appId: '1:161260576816:ios:af2de013349af0ed210df5',
    messagingSenderId: '161260576816',
    projectId: 'ai-chatbot-505a7',
    storageBucket: 'ai-chatbot-505a7.firebasestorage.app',
    androidClientId: '161260576816-3a6cr6minc4r98s02b51m8kjqogj06if.apps.googleusercontent.com',
    iosClientId: '161260576816-gn0rm4mhjbhh36b3fcgulbtmj162fbi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatbot',
  );

}